### ISSUE TITLE
schedule command /w tasklist

### ISSUE THREAD

**Issue by brian-stoker** [brian-stoker/stoked#6]
### Search keywords

schedule command tasklist

### Latest version

- [x] I have tested the latest version

### Summary

This would be an enhancement to the schedule command feature request that allows the user to provide a series of ordered tasks each represented by an individual prompt file, a json file, or a yaml file. Syntax looks like this:

### Examples

text:
```shell
stoked schedule [job-name] 0 0 * * * ./do_this_at_midnight.txt ./and_then_do_this.txt ./and_then_this.txt
```
json:
```shell
stoked schedule [job-name] 0 0 * * * ./midnight_job.json
```

```json
{
  "tasks": [
    {
      "name": "build tech updates email",
      "prompt": "create a reading list for any new technology news that seems relevant to me and send me an email with the list"
    },
    {
      "name": "schedule prep",
      "prompt": "read my scheudle for the next 3 days and give me a list of things that i should prepare for today in order to have successful tasks"
    }
  ]
}
```

yaml:
```shell
stoked schedule [job-name] 0 0 * * * ./midnight_job.yml
```

```yaml
---
tasks:
- name: build tech updates email
  prompt: create a reading list for any new technology news that seems relevant to
    me and send me an email with the list
- name: schedule prep
  prompt: read my scheudle for the next 3 days and give me a list of things that i
    should prepare for today in order to have successful tasks
```
