### ISSUE TITLE
schedule command /w tasklist & i/o

### ISSUE THREAD

**Issue by brian-stoker** [brian-stoker/stoked#7]
### Search keywords

schedule command tasklist input output io

### Latest version

- [x] I have tested the latest version

### Summary

add named inputs and outputs to json and yaml task definitions.. the inputs can reference outputs from tasks in the same list which will change  

### Examples

```json
{
   "tasks":[
      {
         "name":"build tech updates email",
         "prompt":"create a reading list for any new technology news that seems relevant to me and send me an email with the list",
         "inputs":[
            {
               "url":"https://myfavoritetechnewssource.com"
            }
         ],
         "outputs":[
            {
              "techUpdatesEmail":{ "type": "email" }
            }
         ]
      },
      {
         "name":"schedule prep",
         "prompt":"read my scheudle for the next 3 days and give me a list of things that i should prepare for today in order to have successful tasks"
      }
   ]
}
```

yaml:
```yaml
---
tasks:
- name: build tech updates email
  prompt: create a reading list for any new technology news that seems relevant to
    me and send me an email with the list
  inputs:
  - url: https://myfavoritetechnewssource.com
  outputs:
  - techUpdatesEmail:
      type: email
- name: schedule prep
  prompt: read my scheudle for the next 3 days and give me a list of things that i
    should prepare for today in order to have successful tasks
```
